# Generated by Django 5.0.9 on 2024-11-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArbitrageOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_from', models.CharField(max_length=100)),
                ('exchange_to', models.CharField(max_length=100)),
                ('trading_pair', models.CharField(max_length=20)),
                ('buy_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('sell_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('profit', models.DecimalField(decimal_places=4, max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('exchange_from', 'exchange_to', 'trading_pair')},
            },
        ),
    ]
