# Generated by Django 5.0.9 on 2024-11-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitrageopportunity',
            name='buy_price',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='arbitrageopportunity',
            name='exchange_from',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='arbitrageopportunity',
            name='exchange_to',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='arbitrageopportunity',
            name='profit',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='arbitrageopportunity',
            name='sell_price',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
    ]
