# Generated by Django 5.0.9 on 2024-11-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrage', '0002_alter_arbitrageopportunity_buy_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitrageopportunity',
            name='buy_price',
            field=models.DecimalField(decimal_places=20, max_digits=50),
        ),
        migrations.AlterField(
            model_name='arbitrageopportunity',
            name='profit',
            field=models.DecimalField(decimal_places=20, max_digits=50),
        ),
        migrations.AlterField(
            model_name='arbitrageopportunity',
            name='sell_price',
            field=models.DecimalField(decimal_places=20, max_digits=50),
        ),
    ]
